DROP TABLE IF EXISTS TBL_STOCKTRADE;

CREATE TABLE TBL_STOCKTRADE (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  type VARCHAR(250) NOT NULL,
  user_id VARCHAR(250) NOT NULL,
  symbol VARCHAR(250) NOT NULL,
  shares INTEGER(100) NOT NULL CHECK (shares <= 100),
  price INTEGER(100) NOT NULL,
  time_stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);